# Generated by Django 3.2.16 on 2022-10-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=None, verbose_name='Новостройка'),
        ),
    ]
