# Generated by Django 3.2.16 on 2022-10-14 20:47

from django.db import migrations

def get_type_of_building(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    for flat in Flat.objects.all():
        flat.new_building = True if flat.construction_year>=2015 else False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(get_type_of_building)
    ]
