# Generated by Django 3.2.16 on 2022-10-15 14:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20221015_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owners_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
