# Generated by Django 3.2.16 on 2022-10-16 16:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_flat_owners_pure_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО Владельца')),
                ('owners_phonenumber', models.CharField(max_length=10, verbose_name='Номер владельца')),
                ('owners_pure_phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Нормализованный номер владельца')),
                ('flat', models.ManyToManyField(related_name='flat_owner', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
