# Generated by Django 3.2.16 on 2022-10-16 17:05

from django.db import migrations

def load_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owners_pure_phone=flat.owners_pure_phone)





class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner'),
    ]

    operations = [migrations.RunPython(load_owners)
    ]
