# Generated by Django 3.2.16 on 2022-10-16 18:59

from django.db import migrations


def link_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owner_name=owner.owner
        owners_phone = owner.owners_phonenumber
        owners_flat = Flat.objects.get(owner=owner_name, owners_phonenumber=owners_phone)
        owner.flat.add(owners_flat)
        owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20221016_2005'),
    ]

    operations = [migrations.RunPython(link_flats_to_owner)
    ]
