# Generated by Django 3.2.16 on 2022-10-31 20:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20221018_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(max_length=10, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='', max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
