# Generated by Django 3.2.16 on 2022-11-01 18:12

from django.db import migrations


def link_flats_to_owner(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flat_set = Flat.objects.all()

    for flat in flat_set.iterator():
        owner_name = flat.owner
        owners_purephone = flat.owners_pure_phone
        owner = Owner.objects.get(owner=owner_name, owners_pure_phone=owners_purephone)
        flat.flat_owner.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20221031_2344'),
    ]

    operations = [migrations.RunPython(link_flats_to_owner)
    ]
