# Generated by Django 3.2.16 on 2022-11-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20221101_2112'),
    ]

    operations = [migrations.RemoveField(model_name='Flat', name='owners_pure_phone',)
    ]
