# Generated by Django 3.2.16 on 2022-11-01 20:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20221101_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
