# Generated by Django 3.2.16 on 2022-11-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_flat_owners_pure_phone'),
    ]

    operations = [migrations.RemoveField(model_name='Flat', name='owners_phonenumber',),
                  migrations.RemoveField(model_name='Flat', name='owner',)
    ]
