# Generated by Django 2.2.24 on 2022-11-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20221112_0052'),
    ]

    operations = [ migrations.RenameField(
        model_name='Owner',
        old_name='owners_phonenumber',
        new_name='owners_phone'
    )
    ]
