# Generated by Django 2.2.24 on 2022-11-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20221112_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phone',
            new_name='phone',
        ),
    ]
