# Generated by Django 2.2.24 on 2022-11-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_auto_20221112_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='phone',
            new_name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='owners_flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
