# Generated by Django 2.2.24 on 2022-11-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20221112_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats'
        ),
    ]
