# Generated by Django 4.1.3 on 2022-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0029_auto_20221112_0139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="has_balcony",
            field=models.BooleanField(
                db_index=True, null=True, verbose_name="Наличие балкона"
            ),
        ),
    ]
