# Generated by Django 4.1.3 on 2022-11-18 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0030_alter_flat_has_balcony"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="flat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaint",
                to="property.flat",
                verbose_name="Квартира, на которую пожаловались",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_complaint",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто пожаловался",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="flats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто лайкнул",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="flat",
            field=models.ManyToManyField(
                related_name="owners",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
